#!/usr/bin/env bash

file="$1"
case "$file" in
  *.tar.bz2)   tar xjf "$file"   ;;
  *.tar.gz)    tar xzf "$file"   ;;
  *.bz2)       bunzip2 "$file"   ;;
  *.rar)       unrar x "$file"   ;;
  *.gz)        gunzip "$file"    ;;
  *.tar)       tar xf "$file"    ;;
  *.tbz2)      tar xjf "$file"   ;;
  *.tgz)       tar xzf "$file"   ;;
  *.zip)       unzip "$file"     ;;
  *.7z)        7z x "$file"      ;;
  *)           echo "Unknown file type: $file" ;;
esac

